name: Node
on:
  push:
    branches:
      - master
      - main

jobs:
  nodejob:
    runs-on: ubuntu-latest
    env:
      REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12.17.0'

    - name: npm install
      run: npm install

    - name: Install ubuntu package
      run: |
        sudo apt-get update && sudo apt-get install calibre
        sudo apt-get install fonts-takao-mincho fonts-takao

    - name: Generate PDF
      run: npm run generate

    - name: Git commit and push
      run: |
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git status
        git commit -m 'generate PDF' && git push ${REPO} ${{github.event.pull_request.head.ref}}
